language: python
python:
  - '2.7'
install:
  - pip install .
script:
  - python setup.py test
addons:
  apt:
    packages:
      - python-dbus
virtualenv:
  system_site_packages: true
deploy:
  provider: pypi
  user: friskby
  password:
    secure: "J5i6lpoePjw9lx/XKVo1OFC0ahuZ9vZtCXJeQ40KYm6CG867/yn6re7HVmzffHxOIGnTp9Pn1hZVXwIFf3MIMK0rfKvPBnuXW5KCh7AowRHICGimBhumO1dSx5zifTKizdTJESL9ys/hsloQETu+hLw0m2gzdfnfR+b5dGSTIfpl7Mf0FClSrH1ZeNJxQNLzVx6zUF6e4ZBib2KS2oTj6VBuChH2cRirDxwqruHXjoy/QuBUJ3c2K1vp/cZqvpAoruY3Z23xKyV4rEyjBqzhrw6muCuSR/MqL5b+TJSQlr+/0Yx3a4J3qzKu8FOUttgrJZLbfzisidGZaDblmxJHfz2e67hMFD8PsHSq+khqjkITzqtj8JK3mhqggK6TpPQe2sPCa06gP+JTLs4AO198F/YYA5Yv3Xsvn+i13Bbth4cGkF/sPLsRaKtz1HAlfrxgAL3apaM8Cpb+i6EjDMDRPBhS4lbP1SHHuEl0QIYsZISVED0DFglIpFIEyt5wvjyydvCbnspi5gkHlqeJfQ3z/kEC8Ok0lEJ1u9WCOBJkOBJjFtj/RfPzO2yC03crBskTwIQoXXV3QqqdSxspk6ewLBIk8olUhVt/X5pGYINQ7hTqXHX7tRF5QikrYhC9jFLWIRqme9/Ljt6TnR2TBPUTfy2A5xSeZ5AM5R86MdhYw/o="
  on:
    branch: master
    distributions: sdist bdist_wheel
