language: python
env:
  global:
    - PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages/
python:
  - "2.7"
dist: trusty
install:
  - pip install --upgrade pip setuptools distribute
  - pip install dbus-python
  - pip install .
script:
  - python setup.py test
